### ISSUE TITLE
🇺🇸 English support

### ISSUE THREAD

**Issue by FMGordillo** [joelalejandro/afip-qr-component#1]
I am willing to help, if needed ✋ 
------
Estoy dispuesto a ayudar si necesitás! ✋

**Comment by joelalejandro** [comment]
Hey @FMGordillo! Thanks for proposing this. Can you elaborate a bit more about how'd we support English in this case? The component has a customizable `title` page. Keep in mind that this has *no* control over the `qr.afip.gov.ar` site.

**Comment by FMGordillo** [comment]
It was more related to the documentation itself (`README`, comments, that sort of stuff). I am reading again my attempt of issue and I forgot to put a description, my bad! :cry:

**Comment by joelalejandro** [comment]
That's alright, @FMGordillo. Feel free to create a `README.en.md`, and we can link both REAME files between them to switch languages :D

**Comment by FMGordillo** [comment]
Resolved at #4
